<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kenedith Méndez - Gutiérrez">

<title>Estadística Inferencial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Guia2_pHR_files/libs/clipboard/clipboard.min.js"></script>
<script src="Guia2_pHR_files/libs/quarto-html/quarto.js"></script>
<script src="Guia2_pHR_files/libs/quarto-html/popper.min.js"></script>
<script src="Guia2_pHR_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Guia2_pHR_files/libs/quarto-html/anchor.min.js"></script>
<link href="Guia2_pHR_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Guia2_pHR_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Guia2_pHR_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Guia2_pHR_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Guia2_pHR_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #1b4332;
      }

      .quarto-title-block .quarto-title-banner {
        color: #1b4332;
background: #c7f9cc;
      }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Estadística Inferencial</h1>
            <p class="subtitle lead">Prueba de hipótesis con R y RStudio</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Kenedith Méndez - Gutiérrez </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#introducción." id="toc-introducción." class="nav-link active" data-scroll-target="#introducción.">Introducción.</a>
  <ul>
  <li><a href="#sec-type-test" id="toc-sec-type-test" class="nav-link" data-scroll-target="#sec-type-test">Tipos de tests estadísticos.</a>
  <ul>
  <li><a href="#pruebas-paramétricas." id="toc-pruebas-paramétricas." class="nav-link" data-scroll-target="#pruebas-paramétricas.">Pruebas paramétricas.</a></li>
  <li><a href="#pruebas-no-paramétricas" id="toc-pruebas-no-paramétricas" class="nav-link" data-scroll-target="#pruebas-no-paramétricas">Pruebas no paramétricas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparación-de-medias---diseño-de-muestras-independientes." id="toc-comparación-de-medias---diseño-de-muestras-independientes." class="nav-link" data-scroll-target="#comparación-de-medias---diseño-de-muestras-independientes.">Comparación de medias - Diseño de muestras independientes.</a>
  <ul>
  <li><a href="#contexto." id="toc-contexto." class="nav-link" data-scroll-target="#contexto.">Contexto.</a></li>
  <li><a href="#ejecución-de-la-prueba-de-hipótesis-paso-a-paso." id="toc-ejecución-de-la-prueba-de-hipótesis-paso-a-paso." class="nav-link" data-scroll-target="#ejecución-de-la-prueba-de-hipótesis-paso-a-paso.">Ejecución de la prueba de hipótesis paso a paso.</a>
  <ul>
  <li><a href="#paso-1.-descripción-del-planteamiento." id="toc-paso-1.-descripción-del-planteamiento." class="nav-link" data-scroll-target="#paso-1.-descripción-del-planteamiento.">Paso 1. Descripción del planteamiento.</a></li>
  <li><a href="#paso-2.-carge-de-librerías-y-datos." id="toc-paso-2.-carge-de-librerías-y-datos." class="nav-link" data-scroll-target="#paso-2.-carge-de-librerías-y-datos.">Paso 2. Carge de librerías y Datos.</a>
  <ul class="collapse">
  <li><a href="#librerías." id="toc-librerías." class="nav-link" data-scroll-target="#librerías.">2.1 Librerías.</a></li>
  <li><a href="#datos." id="toc-datos." class="nav-link" data-scroll-target="#datos."><strong>2.2 Datos.</strong></a></li>
  <li><a href="#ajustar-los-datos." id="toc-ajustar-los-datos." class="nav-link" data-scroll-target="#ajustar-los-datos.">2.3. Ajustar los datos.</a></li>
  </ul></li>
  <li><a href="#paso-3.-verificación-de-supuestos." id="toc-paso-3.-verificación-de-supuestos." class="nav-link" data-scroll-target="#paso-3.-verificación-de-supuestos.">Paso 3. Verificación de supuestos.</a>
  <ul class="collapse">
  <li><a href="#prueba-de-normalidad." id="toc-prueba-de-normalidad." class="nav-link" data-scroll-target="#prueba-de-normalidad.">3.1 Prueba de normalidad.</a>
  <ul class="collapse">
  <li><a href="#métodos-gráficos." id="toc-métodos-gráficos." class="nav-link" data-scroll-target="#métodos-gráficos.">3.1.1. Métodos gráficos.</a></li>
  <li><a href="#método-análitico---test-de-normalidad-shapiro-wilks." id="toc-método-análitico---test-de-normalidad-shapiro-wilks." class="nav-link" data-scroll-target="#método-análitico---test-de-normalidad-shapiro-wilks.">3.1.2. Método análitico - test de normalidad shapiro &amp; wilks.</a></li>
  </ul></li>
  <li><a href="#prueba-de-homocedasticidad." id="toc-prueba-de-homocedasticidad." class="nav-link" data-scroll-target="#prueba-de-homocedasticidad.">3.2. Prueba de homocedasticidad.</a></li>
  </ul></li>
  <li><a href="#paso-4.-test-de-contraste." id="toc-paso-4.-test-de-contraste." class="nav-link" data-scroll-target="#paso-4.-test-de-contraste.">Paso 4. Test de contraste.</a></li>
  <li><a href="#paso-5.-efecto-y-potencia." id="toc-paso-5.-efecto-y-potencia." class="nav-link" data-scroll-target="#paso-5.-efecto-y-potencia.">Paso 5. Efecto y potencia.</a></li>
  <li><a href="#anexos.-resultados-descriptivos." id="toc-anexos.-resultados-descriptivos." class="nav-link" data-scroll-target="#anexos.-resultados-descriptivos.">Anexos. Resultados descriptivos.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparación-de-medias---diseño-de-muestras-pareadas." id="toc-comparación-de-medias---diseño-de-muestras-pareadas." class="nav-link" data-scroll-target="#comparación-de-medias---diseño-de-muestras-pareadas.">Comparación de medias - Diseño de muestras pareadas.</a>
  <ul>
  <li><a href="#contexto.-1" id="toc-contexto.-1" class="nav-link" data-scroll-target="#contexto.-1">Contexto.</a></li>
  <li><a href="#ejecución-de-la-prueba-de-hipótesis-paso-a-paso.-1" id="toc-ejecución-de-la-prueba-de-hipótesis-paso-a-paso.-1" class="nav-link" data-scroll-target="#ejecución-de-la-prueba-de-hipótesis-paso-a-paso.-1">Ejecución de la prueba de hipótesis paso a paso.</a>
  <ul>
  <li><a href="#paso-1.-descripción-del-planteamiento.-1" id="toc-paso-1.-descripción-del-planteamiento.-1" class="nav-link" data-scroll-target="#paso-1.-descripción-del-planteamiento.-1">Paso 1. Descripción del planteamiento.</a></li>
  <li><a href="#paso-2.-carge-de-librerías-y-datos.-1" id="toc-paso-2.-carge-de-librerías-y-datos.-1" class="nav-link" data-scroll-target="#paso-2.-carge-de-librerías-y-datos.-1">Paso 2. Carge de librerías y Datos.</a>
  <ul class="collapse">
  <li><a href="#librerías.-1" id="toc-librerías.-1" class="nav-link" data-scroll-target="#librerías.-1">2.1. Librerías.</a></li>
  <li><a href="#datos.-1" id="toc-datos.-1" class="nav-link" data-scroll-target="#datos.-1">2.2 Datos.</a></li>
  <li><a href="#ajustar-los-datos.-1" id="toc-ajustar-los-datos.-1" class="nav-link" data-scroll-target="#ajustar-los-datos.-1">2.3. Ajustar los datos.</a></li>
  </ul></li>
  <li><a href="#paso-3.-verificación-de-supuestos.-1" id="toc-paso-3.-verificación-de-supuestos.-1" class="nav-link" data-scroll-target="#paso-3.-verificación-de-supuestos.-1">Paso 3. Verificación de supuestos.</a>
  <ul class="collapse">
  <li><a href="#prueba-de-normalidad---métodos-gráficos." id="toc-prueba-de-normalidad---métodos-gráficos." class="nav-link" data-scroll-target="#prueba-de-normalidad---métodos-gráficos.">3.1. Prueba de normalidad - Métodos gráficos.</a></li>
  <li><a href="#prueba-de-normalidad---test-de-normalidad-shapiro-wilks." id="toc-prueba-de-normalidad---test-de-normalidad-shapiro-wilks." class="nav-link" data-scroll-target="#prueba-de-normalidad---test-de-normalidad-shapiro-wilks.">3.1. Prueba de normalidad - test de normalidad shapiro &amp; wilks.</a></li>
  </ul></li>
  <li><a href="#paso-4.-test-de-contraste.-1" id="toc-paso-4.-test-de-contraste.-1" class="nav-link" data-scroll-target="#paso-4.-test-de-contraste.-1">Paso 4. Test de contraste.</a></li>
  <li><a href="#paso-5.-efecto-y-potencia.-1" id="toc-paso-5.-efecto-y-potencia.-1" class="nav-link" data-scroll-target="#paso-5.-efecto-y-potencia.-1">Paso 5. Efecto y potencia.</a></li>
  <li><a href="#anexos.-resultados-descriptivos.-1" id="toc-anexos.-resultados-descriptivos.-1" class="nav-link" data-scroll-target="#anexos.-resultados-descriptivos.-1">Anexos. Resultados descriptivos.</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<style type="text/css">
  body{
  font-family: Georgia;
  font-size: 12pt;
  text-align: justify;
}
  h1 {
  color: #004b23;
  font-size: 22pt;
  font-family: Georgia;
  text-align: left;
}
  h2 {
  color: #004b23;
  font-size:18pt;
  font-family: Georgia;
  text-align: left;
  font-weight: bold;
}
  h3{ 
  color: #006400;
  font-size:14pt;
  font-family: Georgia;
  text-align: left;
  font-weight: bold;
}
 h4{ 
  color: #006400;
  font-size:12pt;
  font-family: Georgia;
  text-align: left;
  font-weight: bold;
}
 h5{ 
  color: #black;
  font-size:12pt;
  font-family: Georgia;
  text-align: left;
  font-weight: bold;
}
</style>
<section id="introducción." class="level1">
<h1>Introducción.</h1>
<p>Cuando se trata de comparar dos grupos en un estudio, una de las preguntas más comunes es si hay una diferencia significativa entre sus medias. Las pruebas de estadísticas para el contraste de hipótesis sobre las medias es un análisis crucial en múltiples disciplinas, desde la biología hasta la psicología, ya que permiten determinar si las diferencias observadas entre los grupos son lo suficientemente grandes como para ser consideradas significativas, o si podrían haberse producido por azar. Dependiendo de las características de los datos, como la distribución y la varianza, se pueden emplear diferentes test, ya sean paramétricos o no paramétricos, para llevar a cabo esta comparación.</p>
<section id="sec-type-test" class="level2">
<h2 class="anchored" data-anchor-id="sec-type-test">Tipos de tests estadísticos.</h2>
<section id="pruebas-paramétricas." class="level3">
<h3 class="anchored" data-anchor-id="pruebas-paramétricas.">Pruebas paramétricas.</h3>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Estas pruebas asumen que la distribución de los datos siguen un comportamiento normal.</p>
</div>
</div>
<ul>
<li><p><strong><em>Prueba t para 2 muestras independientes:</em></strong></p>
<ul>
<li><p><strong>Propósito</strong>: Compara las medias de dos grupos.</p></li>
<li><p><strong>Supuestos</strong>: Distribución normal de los datos de ambas muestras y que las varianzas sean homogéneas entre ambos grupos (homocedasticidad).</p></li>
<li><p><strong>Función en R</strong>: <code>t.test()</code> con argumentos <code>paired=FALSE</code> , <code>var.equal=TRUE</code> y <code>alternative</code> para indicar el tipo de contraste, <code>alternative="two.sided"</code> para dos colas, <code>alternative="greater"</code> para unilateral a la derecha, y <code>alternative="less"</code>para unilateral a izquierda.</p></li>
</ul></li>
<li><p><strong><em>Prueba t welch para 2 muestras independientes:</em></strong></p>
<ul>
<li><p><strong>Propósito</strong>: Compara las medias de dos grupos.</p></li>
<li><p><strong>Supuestos</strong>: Distribución normal de los datos de ambas muestras y que las varianzas sean diferentes entre ambos grupos (heterocedasticidad).</p></li>
<li><p><strong>Función en R</strong>: <code>t.test()</code> con argumentos <code>paired=FALSE</code> , <code>var.equal=FALSE</code> y <code>alternative</code> para indicar el tipo de contraste, <code>alternative="two.sided"</code> para dos colas, <code>alternative="greater"</code> para unilateral a la derecha, y <code>alternative="less"</code>para unilateral a izquierda.</p></li>
</ul></li>
<li><p><strong><em>Prueba t de Student para muestras pareadas:</em></strong></p>
<ul>
<li><p><strong>Propósito</strong>: Compara las medias de dos grupos de mediciones relacionadas (ejemplo., mediciones antes y después del tratamiento en los mismos sujetos).</p></li>
<li><p><strong>Supuestos</strong>: Normalidad de las diferencias entre las mediciones.</p></li>
<li><p><strong>Función en R</strong>: <code>t.test()</code> con argumentos <code>paired=TRUE</code> y <code>alternative</code> para indicar el tipo de contraste, <code>alternative="two.sided"</code> para dos colas, <code>alternative="greater"</code> para unilateral a la derecha, y <code>alternative="less"</code>para unilateral a izquierda.</p></li>
</ul></li>
</ul>
</section>
<section id="pruebas-no-paramétricas" class="level3">
<h3 class="anchored" data-anchor-id="pruebas-no-paramétricas">Pruebas no paramétricas</h3>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Estas pruebas no asumen una distribución de los datos ajustada a la distribución normal y son la alternativa a las pruebas paramétricas.</p>
</div>
</div>
<ul>
<li><p><strong><em>Prueba de Mann-Whitney Wilcoxon:</em></strong></p>
<ul>
<li><p><strong>Propósito</strong>: Compara las medianas de dos grupos.</p></li>
<li><p><strong>Uso</strong>: Alternativa a la prueba t para muestras independientes cuando los datos no son normales.</p></li>
<li><p><strong>Supuestos</strong>: No requiere normalidad, pero los datos deben ser ordinales o continuos.</p></li>
<li><p><strong>Función en R</strong>: <code>wilcox.test()</code> con argumentos <code>paired=FALSE</code> y <code>alternative</code> para indicar el tipo de contraste, <code>alternative="two.sided"</code> para dos colas, <code>alternative="greater"</code> para unilateral a la derecha, y <code>alternative="less"</code>para unilateral a izquierda.</p></li>
</ul></li>
<li><p><strong><em>Prueba de Wilcoxon:</em></strong></p>
<ul>
<li><p><strong>Propósito</strong>: Compara las medianas de dos grupos de mediciones relacionadas.</p></li>
<li><p><strong>Uso</strong>: Alternativa a la prueba t para muestras pareadas cuando los datos no son normales.</p></li>
<li><p><strong>Supuestos</strong>: No requiere normalidad, pero los datos deben ser ordinales o continuos.</p></li>
<li><p><strong>Función en R</strong>: <code>wilcox.test()</code> con argumentos <code>paired=TRUE</code> y <code>alternative</code> para indicar el tipo de contraste, <code>alternative="two.sided"</code> para dos colas, <code>alternative="greater"</code> para unilateral a la derecha, y <code>alternative="less"</code>para unilateral a izquierda.</p></li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="comparación-de-medias---diseño-de-muestras-independientes." class="level1">
<h1>Comparación de medias - Diseño de muestras independientes.</h1>
<section id="contexto." class="level2">
<h2 class="anchored" data-anchor-id="contexto.">Contexto.</h2>
<p>En un estudio sobre el habito de fumar y sus efectos sobre los patrones de sueño una de las variables importantes es el tiempo que transcure antes de quedarse dormido. En este contexto consideraremos que se extrae una muestra de tamaño 12 de una población de fumadores y otra muestra de tamaño 15 de una población de no fumadores. A ambos grupos se les monitorea el sueño y se les registra el tiempo en minutos transcurrido antes de conciliar el sueño, los datos fueron los siguientes:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Fumadores (S)</th>
<th style="text-align: center;">No Fumadores (N)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">69.3</td>
<td style="text-align: center;">28.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">56.0</td>
<td style="text-align: center;">25.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">22.1</td>
<td style="text-align: center;">26.4</td>
</tr>
<tr class="even">
<td style="text-align: center;">47.6</td>
<td style="text-align: center;">34.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">53.2</td>
<td style="text-align: center;">29.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">48.1</td>
<td style="text-align: center;">28.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">23.3</td>
<td style="text-align: center;">38.5</td>
</tr>
<tr class="even">
<td style="text-align: center;">13.8</td>
<td style="text-align: center;">30.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">52.7</td>
<td style="text-align: center;">30.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">34.4</td>
<td style="text-align: center;">31.8</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60.2</td>
<td style="text-align: center;">41.6</td>
</tr>
<tr class="even">
<td style="text-align: center;">43.8</td>
<td style="text-align: center;">21.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">NA</td>
<td style="text-align: center;">36.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">NA</td>
<td style="text-align: center;">37.9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">NA</td>
<td style="text-align: center;">13.9</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="ejecución-de-la-prueba-de-hipótesis-paso-a-paso." class="level2">
<h2 class="anchored" data-anchor-id="ejecución-de-la-prueba-de-hipótesis-paso-a-paso.">Ejecución de la prueba de hipótesis paso a paso.</h2>
<section id="paso-1.-descripción-del-planteamiento." class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-descripción-del-planteamiento.">Paso 1. Descripción del planteamiento.</h3>
<ul>
<li><p>Tipo de estudio: Observacional</p></li>
<li><p>Tipo de diseño. Diseño unifactorial de 2 muestras independientes completamente aleatorio.</p></li>
<li><p>Elementos del diseño:</p>
<ul>
<li><p>Factor: Grupo.</p></li>
<li><p>Niveles del factor: 2</p></li>
<li><p>Tratamientos: Fumadores (S), No fumadores (N).</p></li>
<li><p>Variable de respuesta: Tiempo en minutos transcurrido antes de conciliar el sueño.</p></li>
<li><p>Réplicas: n=12 para (S), n=15 para (N)</p></li>
<li><p>Unidad experimental: Cada individuo en estudio (N=27 total).</p></li>
</ul></li>
<li><p>Hipótesis estadísticas.</p>
<ul>
<li><p>Ho: El tiempo promedio en minutos transcurrido antes de conciliar el sueño entre fumadores y no fumadores es el mismo.</p></li>
<li><p>H1: El tiempo promedio en minutos transcurrido antes de conciliar el sueño entre fumadores y no fumadores es diferente.</p></li>
</ul></li>
<li><p>Tipo de contraste: Bilateral</p></li>
</ul>
</section>
<section id="paso-2.-carge-de-librerías-y-datos." class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-carge-de-librerías-y-datos.">Paso 2. Carge de librerías y Datos.</h3>
<section id="librerías." class="level4">
<h4 class="anchored" data-anchor-id="librerías.">2.1 Librerías.</h4>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#Para gráficos</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co">#Para gráfico Q-Q</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#Para manipular datos.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qqplotr) <span class="co">#Para gráfico Q-Q</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="datos." class="level4">
<h4 class="anchored" data-anchor-id="datos."><strong>2.2 Datos.</strong></h4>
<p>En esta oportunidad vamos a ingresar los datos creando dos vectores, uno para cada conjunto de datos correspondientes a cada grupo.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Fumadores<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">69.3</span>,<span class="fl">56.0</span>,<span class="fl">22.1</span>,<span class="fl">47.6</span>,<span class="fl">53.2</span>,<span class="fl">48.1</span>,<span class="fl">23.3</span>,<span class="fl">13.8</span>,<span class="fl">52.7</span>,<span class="fl">34.4</span>,<span class="fl">60.2</span>,<span class="fl">43.8</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>No.Fumadores<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">28.6</span>,<span class="fl">25.1</span>,<span class="fl">26.4</span>,<span class="fl">34.9</span>,<span class="fl">29.8</span>,<span class="fl">28.4</span>,<span class="fl">38.5</span>,<span class="fl">30.2</span>,<span class="fl">30.6</span>,<span class="fl">31.8</span>,<span class="fl">41.6</span>,<span class="fl">21.1</span>,<span class="fl">36.0</span>,<span class="fl">37.9</span>,<span class="fl">13.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="ajustar-los-datos." class="level4">
<h4 class="anchored" data-anchor-id="ajustar-los-datos.">2.3. Ajustar los datos.</h4>
<p>Como los datos de las variable de respuesta estan en forma de vectores separados, se debe agrupar toda la información en un libro de datos. Para ello creamos primero un vector con la información del factor con la función concatenar <code>c()</code>, luego agrupamos todo los valores (Factor y variable de respuesta) con la función <code>data.frame()</code> y finalmente cambiamos la naturaleza del factor de chr con la función <code>as.factor()</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Grupo<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Fumadores"</span>,<span class="dv">12</span>),<span class="fu">rep</span>(<span class="st">"No fumadores"</span>,<span class="dv">15</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Datos<span class="ot">&lt;-</span><span class="fu">data.frame</span>(Grupo,<span class="at">Tiempo=</span><span class="fu">c</span>(Fumadores,No.Fumadores))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Datos<span class="sc">$</span>Grupo<span class="ot">&lt;-</span><span class="fu">as.factor</span>(Datos<span class="sc">$</span>Grupo)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Grupo Tiempo
1 Fumadores   69.3
2 Fumadores   56.0
3 Fumadores   22.1
4 Fumadores   47.6
5 Fumadores   53.2
6 Fumadores   48.1</code></pre>
</div>
</div>
</section>
</section>
<section id="paso-3.-verificación-de-supuestos." class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-verificación-de-supuestos.">Paso 3. Verificación de supuestos.</h3>
<p>Puesto que el parámetro de interes es la diferencia de medias para un diseño de dos muestras independientes con varianzas desconocidas se deben verificar el comportamiento de la variable de respuesta en ambas muestras en cuanto a simétria (Normalidad) y variación (Homocedasticidad). En caso de no poder respaldar el supuesto de normalidad no se requiere verificar lo homocedasticidad.</p>
<section id="prueba-de-normalidad." class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-normalidad.">3.1 Prueba de normalidad.</h4>
<section id="métodos-gráficos." class="level5">
<h5 class="anchored" data-anchor-id="métodos-gráficos.">3.1.1. Métodos gráficos.</h5>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráficos.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Histogram</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos, <span class="fu">aes</span>(<span class="at">x =</span> Tiempo))<span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">6</span>, <span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">color=</span><span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>Grupo,<span class="at">ncol =</span> <span class="dv">2</span>,<span class="at">scales=</span><span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Frecuencia"</span>)<span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Q-Q </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos, <span class="fu">aes</span>(<span class="at">sample =</span> Tiempo))<span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_band</span>(<span class="at">distribution =</span> <span class="st">"norm"</span>,<span class="at">fill=</span><span class="st">"#faf3dd"</span>)<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_point</span>(<span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">shape=</span><span class="dv">21</span>)<span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">distribution =</span> <span class="st">"norm"</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>Grupo,<span class="at">ncol =</span> <span class="dv">2</span>,<span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="método-análitico---test-de-normalidad-shapiro-wilks." class="level5">
<h5 class="anchored" data-anchor-id="método-análitico---test-de-normalidad-shapiro-wilks.">3.1.2. Método análitico - test de normalidad shapiro &amp; wilks.</h5>
<p>El test de normalidad shapiro &amp; wilks contrasta si las observaciones de una muestra aleatoria provino de un población con distribución normal. Este test es potente para probar la normalidad de un conjunto de datos siempre que se tenga máximo 2000 valores muestrales. A diferencia de otros test como el test K-S, no permite probar la bondad de ajuste de los datos para distribuciones distintas de la distribución normal.</p>
<p><strong>Estadístico de prueba:</strong></p>
<p><span class="math display">\[
W=\frac{b^2}{\sum(x_i-\bar{x})^2}
\]</span></p>
<p><strong>Hipótesis estadísticas:</strong></p>
<p><span class="math inline">\(H_0:=\)</span> Los datos provienen de una población que se ajusta a la distribución normal. <span class="math inline">\(H_1:=\)</span> Los datos provienen de una población que no se ajusta a la distribución normal.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(Fumadores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  Fumadores
W = 0.9452, p-value = 0.5682</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(No.Fumadores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  No.Fumadores
W = 0.96585, p-value = 0.7925</code></pre>
</div>
</div>
<p><strong>Interpretación.</strong> Vemos que a un nivel de significancia del <span class="math inline">\(\alpha=05\)</span> el test de normalidad shapiro &amp; wilks no rechaza la idea de que la distribución del tiempo en minutos que transcurre antes de conciliar el sueño se ajusta a la distribución normal tanto para el grupo de fumadores, <span class="math inline">\(\ W(12)=0.94, p=0.57\)</span> como para el grupo de no fumadores, <span class="math inline">\(\ W(15)=0.97, p=0.79\)</span>.</p>
</section>
</section>
<section id="prueba-de-homocedasticidad." class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-homocedasticidad.">3.2. Prueba de homocedasticidad.</h4>
<p>Puesto que no hay suficiente evidencia para rechazar el cumplimiento del supuesto de normalidad, se hace necesario que determinemos si la variación en el tiempo que transcure antes de conciliar el sueño es o no igual entre los dos grupos, para ello haremos uso de la función <code>"var.test()"</code> que realiza la prueba de razón F.</p>
<p><strong>Estadístico de prueba:</strong></p>
<p><span class="math display">\[
F=\frac{S_1^2}{S_2^2}
\]</span></p>
<p><strong>Hipótesis estadísticas:</strong></p>
<p><span class="math inline">\(H_0:=\)</span> Las varianzas son iguales.</p>
<p><span class="math inline">\(H_1:=\)</span> Las varianzas son diferentes.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(<span class="at">x =</span>Fumadores ,<span class="at">y=</span>No.Fumadores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  Fumadores and No.Fumadores
F = 5.6327, num df = 11, denom df = 14, p-value = 0.003413
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
  1.820191 18.919318
sample estimates:
ratio of variances 
          5.632744 </code></pre>
</div>
</div>
<p><strong>Interpretación.</strong> La prueba F para dos varianzas arrojo una diferencia significativa a un nivel de signficancia del <span class="math inline">\(\alpha=05\)</span> entre la variación en los tiempos que transcure antes de cociliar el sueño entre fumadores y no fumadores, <span class="math inline">\(\ F(11,14)=5.63, p=0.003\)</span>, que se estima en <span class="math inline">\(\ IC95\%[1.82-18.92]\)</span>, siendo mayor en el grupo de fumadores.</p>
</section>
</section>
<section id="paso-4.-test-de-contraste." class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-test-de-contraste.">Paso 4. Test de contraste.</h3>
<p>De acuerdo con los resulatdos obtenidos en la verficación de supuesos, el tests de contraste adecuado para determinar si existen diferencias estadística entre las medias de ambos grupos es la prueba parámetrica t-welch <strong>(Ver: <a href="#sec-type-test" class="quarto-xref">Section&nbsp;1.1</a>)</strong>. Para ejecutar la prueba haremos uso de la función <code>"t.test()"</code> en donde el argumento lógico <code>"var.equal"</code> equivale a la conclusión obtenida en la prueba de homoedasticidad, dónde se indica <code>"var.equal=FALSE"</code> .</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Fumadores, No.Fumadores,<span class="at">var.equal =</span> <span class="cn">FALSE</span>, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Fumadores and No.Fumadores
t = 2.5654, df = 14.123, p-value = 0.02232
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  2.204378 24.572289
sample estimates:
mean of x mean of y 
 43.70833  30.32000 </code></pre>
</div>
</div>
<p><strong>Interpretación.</strong> La prueba t de welch arrojo una diferencia significativa a un nivel de signficancia del <span class="math inline">\(\alpha=05\)</span> entre los tiempos promedios que transcure antes de cociliar el sueño de fumadores y no fumadores, <span class="math inline">\(\ t(14.123)=2.5654, p=0.02232\)</span>, que se estima en <span class="math inline">\(\ IC95\%[2.204-24.572]\)</span>, siendo mayor en el grupo de fumadores.</p>
</section>
<section id="paso-5.-efecto-y-potencia." class="level3">
<h3 class="anchored" data-anchor-id="paso-5.-efecto-y-potencia.">Paso 5. Efecto y potencia.</h3>
<p>El Efecto ó el tamaño del efecto y la potencia ó poder estadístico son dos medidas utiles para el diseño estudios. El primero permite evaluar la relevancia práctica de los resultados, mientras que el segundo ayuda a planificar el estudio de manera adecuada, especificamente es emplea para determinar el tamaño de muestra, soportando así la validez de las conclusiones.</p>
<ul>
<li><p><strong><em>Efecto o tamaño del efecto</em></strong>. Magnitud de la diferencia o la fuerza de la relación entre las variables que se estudian. En decir, indica cuán grande es el cambio o la diferencia observada. Existen diversas medidas para cuantificar el tamaño del efecto, en el caso particular de la compración de medias de dos grupos se emplea la d de Cohen, dónde los criterios de interpretación son:</p>
<ul>
<li><p><span class="math inline">\(d \leq 0.2\)</span> : Tamaño del efecto pequeño. La diferencia entre los grupos es pequeña y puede no ser relevante en la práctica.</p></li>
<li><p><span class="math inline">\(\ 0.2 &lt; d &lt; 0.8\)</span> : Tamaño del efecto mediano. La diferencia entre los grupos es moderada y puede tener cierta relevancia práctica.</p></li>
<li><p><span class="math inline">\(d\geq0.8\)</span> : Tamaño del efecto grande. La diferencia entre los grupos es grande y es probable que tenga una relevancia práctica significativa.</p></li>
</ul></li>
<li><p><strong><em>Potencia estadística.</em></strong> Probabilidad de que una prueba estadística detecte un efecto verdadero si este existe en la población. En decir, es la probabilidad de que un estudio encuentre un resultado estadísticamente significativo si realmente hay una diferencia o una relación. La potencia estadística está influenciada por varios factores, incluyendo: el tamaño del efecto, el tamaño de la muestra, el nivel de significación y la varianza en los datos.</p></li>
</ul>
<div class="callout callout-style-simple callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ten en cuenta.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es importante distinguir el tamaño del efecto de la significación estadística. Que un resultado sea estadísticamente significativo no implica necesariamente que el efecto sea grande o relevante en la práctica. Un efecto pequeño puede ser estadísticamente significativo si la muestra es lo suficientemente grande.</p>
</div>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Efecto</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(<span class="at">x =</span> Fumadores, <span class="at">y =</span> No.Fumadores , <span class="at">data =</span> Datos, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">pooled_sd =</span> <span class="cn">FALSE</span>, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
1.03      | [0.14, 1.89]

- Estimated using un-pooled SD.</code></pre>
</div>
</div>
<p><strong>Interpretación.</strong> La d de Cohen obtenida fue de 1.03, lo que indica un tamaño del efecto grande. Con este hallazgo Lla diferencia entre los grupos es grande y es probable que tenga una relevancia práctica significativa.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Potencia</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">1.03</span>,<span class="at">sig.level =</span> <span class="fl">0.05</span>,<span class="at">power =</span> <span class="fl">0.8</span>,<span class="at">type =</span> <span class="st">"two.sample"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample t test power calculation 

              n = 15.817
              d = 1.03
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p><strong>Interpretación.</strong> La prueba de potencia indica que son necesitarías 16 observaciones por grupo (32 en total) para tener el poder estadístico mínimo recomendado (80%) anticipando una diferencia considerable entre las medias de los dos grupos (un tamaño del efecto grande) a un nivel de significancia de 0.05 siguiendo un contraste bilateral.</p>
</section>
<section id="anexos.-resultados-descriptivos." class="level3">
<h3 class="anchored" data-anchor-id="anexos.-resultados-descriptivos.">Anexos. Resultados descriptivos.</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Hacer un gráfico de Cajas.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos,<span class="fu">aes</span>(<span class="at">x =</span> Grupo, <span class="at">y =</span> Tiempo))<span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom=</span><span class="st">'errorbar'</span>, <span class="at">linetype=</span><span class="dv">1</span>, <span class="at">width=</span><span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"#ffa69e"</span>,<span class="at">color=</span><span class="st">"black"</span>,<span class="at">width=</span><span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">size=</span><span class="dv">3</span>, <span class="at">shape=</span><span class="dv">8</span>)<span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Tiempo antes de conciliar el sueño (min)"</span>,<span class="at">x=</span><span class="st">""</span>)<span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_compare_means</span>(<span class="at">method =</span> <span class="st">"t.test"</span>, <span class="at">label =</span> <span class="st">"p.signif"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method.args=</span><span class="fu">list</span>(<span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">var.equal=</span><span class="cn">FALSE</span>),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">comparisons =</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Fumadores"</span>,<span class="st">"No fumadores"</span>)))<span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="cn">NA</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">##  Hacer un gráfico de medias.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos,<span class="fu">aes</span>(<span class="at">x =</span> Grupo, <span class="at">y =</span> Tiempo))<span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">color=</span><span class="st">"black"</span>, <span class="at">width=</span><span class="fl">0.3</span>)<span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_normal,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">geom =</span><span class="st">"errorbar"</span>,<span class="at">width=</span><span class="fl">0.05</span>)<span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span> </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Tiempo antes de conciliar el sueño (min)"</span>,<span class="at">x=</span><span class="st">""</span>)<span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_compare_means</span>(<span class="at">method =</span> <span class="st">"t.test"</span>, <span class="at">label =</span> <span class="st">"p.signif"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method.args=</span><span class="fu">list</span>(<span class="at">alternative =</span> <span class="st">"two.sided"</span>, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">var.equal=</span><span class="cn">FALSE</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">comparisons =</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Fumadores"</span>,<span class="st">"No fumadores"</span>)) )<span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="cn">NA</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de resumen. </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descriptr)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ds_group_summary</span>(<span class="at">data =</span> Datos, <span class="at">group_by =</span> Grupo, <span class="at">cols =</span>  Tiempo)<span class="sc">$</span>stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Statistic/Levels Fumadores No fumadores
1                  Obs     12.00        15.00
2              Minimum     13.80        13.90
3              Maximum     69.30        41.60
4                 Mean     43.71        30.32
5               Median     47.85        30.20
6                 Mode     13.80        13.90
7       Std. Deviation     16.92         7.13
8             Variance    286.18        50.81
9             Skewness     -0.48        -0.62
10            Kurtosis     -0.69         0.76
11      Uncorrected SS  26072.97     14500.82
12        Corrected SS   3147.95       711.28
13     Coeff Variation     38.70        23.51
14     Std. Error Mean      4.88         1.84
15               Range     55.50        27.70
16 Interquartile Range     22.28         8.05</code></pre>
</div>
</div>
<p><strong>Análisis</strong> Para el grupo de estudio de fumadores, el tiempo registado requerido para conciliar el sueño oscilo entre 13.8 y 69.3 min, tomandoles en general alrededor de 43.7 min para conciliar el sueño <span class="math inline">\(\ (SD=16.92)\)</span> y en donde la mitad de los participantes lograron conciliar el sueño en antes de los 47.8 min <span class="math inline">\(\ (IQR=31.6-53.9)\)</span>; en contraste, para los no fumadores el menor tiempo registado antes de conciliar el sueño fue de 13.9 min y el máximo de 41.6, tomandoles en general alrededor de 30.3 min <span class="math inline">\(\ (SD=7.13)\)</span> y en donde la mitad de los participantes lograron conciliar el sueño en antes de los 30.2 min <span class="math inline">\(\ (IQR=27.4-35.5)\)</span>. La prueba de T-welch reflejo una diferencia significativa en los tiempos que transcure antes de cociliar el sueño entre ambos grupos, <span class="math inline">\(\ t(12.5)=2.2456, p=0.04\)</span>, donde aquellas personas que son fumadores tardan más minutos en conciliar el sueño con una diferencia estimada en minutos de <span class="math inline">\(\ IC95\%[2.20-24.57]\)</span> con respecto aquellos que no son fumadores.</p>
</section>
</section>
</section>
<section id="comparación-de-medias---diseño-de-muestras-pareadas." class="level1">
<h1>Comparación de medias - Diseño de muestras pareadas.</h1>
<section id="contexto.-1" class="level2">
<h2 class="anchored" data-anchor-id="contexto.-1">Contexto.</h2>
<p>En un estudio realizado por el Departamento de Nutrición Humana y Alimentos del Virginia Tech se registraron los siguientes datos sobre los residuos de ácido sórbico en jamón, en partes por millón, inmediatamente después de sumergirlo en una solución de sorbato y después de 60 días de almacenamiento:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Al sumergirlo (A)</strong></th>
<th style="text-align: center;"><strong>Después (D)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">224</td>
<td style="text-align: center;">116</td>
</tr>
<tr class="even">
<td style="text-align: center;">270</td>
<td style="text-align: center;">96</td>
</tr>
<tr class="odd">
<td style="text-align: center;">400</td>
<td style="text-align: center;">239</td>
</tr>
<tr class="even">
<td style="text-align: center;">444</td>
<td style="text-align: center;">329</td>
</tr>
<tr class="odd">
<td style="text-align: center;">590</td>
<td style="text-align: center;">437</td>
</tr>
<tr class="even">
<td style="text-align: center;">660</td>
<td style="text-align: center;">597</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1400</td>
<td style="text-align: center;">689</td>
</tr>
<tr class="even">
<td style="text-align: center;">680</td>
<td style="text-align: center;">576</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="ejecución-de-la-prueba-de-hipótesis-paso-a-paso.-1" class="level2">
<h2 class="anchored" data-anchor-id="ejecución-de-la-prueba-de-hipótesis-paso-a-paso.-1">Ejecución de la prueba de hipótesis paso a paso.</h2>
<section id="paso-1.-descripción-del-planteamiento.-1" class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-descripción-del-planteamiento.-1">Paso 1. Descripción del planteamiento.</h3>
<ul>
<li><p>Tipo de estudio: Experimental.</p></li>
<li><p>Tipo de diseño. Diseño unifactorial de 2 muestras independientes completamente aleatorio.</p></li>
<li><p>Elementos del diseño:</p>
<ul>
<li><p>Factor: Momento de medición.</p></li>
<li><p>Niveles del factor: 2</p></li>
<li><p>Tratamientos: al sumergirlo (A), después de 60 día de almacenamiento (D)</p></li>
<li><p>Variable de respuesta: Cantidad de ácido sórbico residual, en partes por millón</p></li>
<li><p>Réplicas: n=8.</p></li>
<li><p>Unidad experimental: Cada muestra de jamón (N=8 total).</p></li>
</ul></li>
<li><p>Hipótesis estadísticas.</p>
<ul>
<li><p>Ho: La cantidad promedio de ácido sórbico residual (ppm) del jamón al sumergirlo en la solución y después de 60 días de almacenamiento es el mismo.</p></li>
<li><p>H1: La cantidad promedio de ácido sórbico residual (ppm) del jamón al sumergirlo en la solución y después de 60 días de almacenamiento es diferente.</p></li>
</ul></li>
<li><p>Tipo de contraste: Bilateral</p></li>
</ul>
</section>
<section id="paso-2.-carge-de-librerías-y-datos.-1" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-carge-de-librerías-y-datos.-1">Paso 2. Carge de librerías y Datos.</h3>
<section id="librerías.-1" class="level4">
<h4 class="anchored" data-anchor-id="librerías.-1">2.1. Librerías.</h4>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#Para gráficos</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co">#Para gráfico Q-Q</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#Para manipular datos.</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qqplotr) <span class="co">#Para gráfico Q-Q</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="datos.-1" class="level4">
<h4 class="anchored" data-anchor-id="datos.-1">2.2 Datos.</h4>
<p>Vamos a ingresar los datos creando dos vectores, uno para cada conjunto de datos correspondientes a cada grupo.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>A<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">224</span>,<span class="dv">270</span>,<span class="dv">400</span>,<span class="dv">444</span>,<span class="dv">590</span>,<span class="dv">660</span>,<span class="dv">1400</span>,<span class="dv">680</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>D<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">116</span>,<span class="dv">96</span>,<span class="dv">239</span>,<span class="dv">329</span>,<span class="dv">437</span>,<span class="dv">597</span>,<span class="dv">689</span>,<span class="dv">576</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="ajustar-los-datos.-1" class="level4">
<h4 class="anchored" data-anchor-id="ajustar-los-datos.-1">2.3. Ajustar los datos.</h4>
<p>Como los datos de las variable de respuesta estan en forma de vectores separados, se debe agrupar toda la información en un libro de datos. Para ello creamos primero un vector con la información del factor con la función concatenar <code>c()</code>, luego agrupamos todo los valores (Factor y variable de respuesta) con la función <code>data.frame()</code> y finalmente cambiamos la naturaleza del factor de chr con la función <code>as.factor()</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>Grupo<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Al sumergirlo"</span>,<span class="dv">8</span>),<span class="fu">rep</span>(<span class="st">"Después de almacenado"</span>,<span class="dv">8</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Datos<span class="ot">&lt;-</span><span class="fu">data.frame</span>(Grupo,<span class="at">Residuos=</span><span class="fu">c</span>(A,D))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>Datos<span class="sc">$</span>Grupo<span class="ot">&lt;-</span><span class="fu">as.factor</span>(Datos<span class="sc">$</span>Grupo)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          Grupo Residuos
1 Al sumergirlo      224
2 Al sumergirlo      270
3 Al sumergirlo      400
4 Al sumergirlo      444
5 Al sumergirlo      590
6 Al sumergirlo      660</code></pre>
</div>
</div>
</section>
</section>
<section id="paso-3.-verificación-de-supuestos.-1" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-verificación-de-supuestos.-1">Paso 3. Verificación de supuestos.</h3>
<p>Puesto que el parámetro de interes es la diferencia de medias para un diseño de muestras pareadas solo se debe verificar el comportamiento de la variable de respuesta en cuanto a simétria (Normalidad) en ambos grupos.</p>
<section id="prueba-de-normalidad---métodos-gráficos." class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-normalidad---métodos-gráficos.">3.1. Prueba de normalidad - Métodos gráficos.</h4>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gráficos.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Histogram</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos, <span class="fu">aes</span>(<span class="at">x =</span> Residuos))<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">6</span>, <span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">color=</span><span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>Grupo,<span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales=</span><span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Frecuencia"</span>)<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Q-Q </span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Datos, <span class="fu">aes</span>(<span class="at">sample =</span> Residuos))<span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_band</span>(<span class="at">distribution =</span> <span class="st">"norm"</span>,<span class="at">fill=</span><span class="st">"#faf3dd"</span>)<span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_point</span>(<span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">shape=</span><span class="dv">21</span>)<span class="sc">+</span> </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">distribution =</span> <span class="st">"norm"</span>)<span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>Grupo,<span class="at">ncol =</span> <span class="dv">2</span>,<span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prueba-de-normalidad---test-de-normalidad-shapiro-wilks." class="level4">
<h4 class="anchored" data-anchor-id="prueba-de-normalidad---test-de-normalidad-shapiro-wilks.">3.1. Prueba de normalidad - test de normalidad shapiro &amp; wilks.</h4>
<p>El test de normalidad shapiro &amp; wilks contrasta si las observaciones de una muestra aleatoria provino de un población con distribución normal. Este test es potente para probar la normalidad de un conjunto de datos siempre que se tenga máximo 2000 valores muestrales. A diferencia de otros test como el test K-S, no permite probar la bondad de ajuste de los datos para distribuciones distintas de la distribución normal.</p>
<p><strong>Estadístico de prueba:</strong></p>
<p>$$</p>
<p>W=</p>
<p>$$</p>
<p><strong>Hipótesis estadísticas:</strong></p>
<p><span class="math inline">\(H_0:=\)</span> Los datos provienen de una población que se ajusta a la distribución normal. <span class="math inline">\(H_1:=\)</span> Los datos provienen de una población que no se ajusta a la distribución normal.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  A
W = 0.83222, p-value = 0.06261</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(D)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  D
W = 0.92984, p-value = 0.5146</code></pre>
</div>
</div>
<p><strong>RESPONDE:</strong> ¿Es posible validar el supuesto de normalidad para ambos conjuntos? Justifique reportando a partir de las salidas.</p>
</section>
</section>
<section id="paso-4.-test-de-contraste.-1" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-test-de-contraste.-1">Paso 4. Test de contraste.</h3>
<p>De acuerdo con los resultados obtenidos en la verificación de supuesos, el test de contraste adecuado para determinar si existen diferencias estadística entre las medias de ambos grupos es una prueba parámetrica llamada prueba t (<strong>Ver: <a href="#sec-type-test" class="quarto-xref">Section&nbsp;1.1</a></strong>). En esta prueba el argumento <code>"paired"</code> de la función <code>"t.test()"</code>, se usa para indicar si el diseño corresponde a un diseño de muestras pareadas <code>"paired=TRUE"</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> A, <span class="at">y =</span> D, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  A and D
t = 2.6731, df = 7, p-value = 0.03186
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
  22.9225 374.3275
sample estimates:
mean difference 
        198.625 </code></pre>
</div>
</div>
<p><strong>RESPONDE:</strong> ¿Es posible afirmar que el tiempo de almacenamiento supone un efecto significativo en la cantidad de residuos de ácido sórbico (ppm)?, de ser así, ¿En cuánto se estima la diferencia? Justifique reportando a partir de las salidas.</p>
</section>
<section id="paso-5.-efecto-y-potencia.-1" class="level3">
<h3 class="anchored" data-anchor-id="paso-5.-efecto-y-potencia.-1">Paso 5. Efecto y potencia.</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Efecto</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cohens_d</span>(<span class="at">x =</span> A, <span class="at">y =</span> D , <span class="at">data =</span> Datos, <span class="at">paired =</span> <span class="cn">TRUE</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |       95% CI
------------------------
0.95      | [0.08, 1.77]</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.t.test</span>(<span class="at">d =</span> <span class="fl">0.95</span>,<span class="at">sig.level =</span> <span class="fl">0.05</span>,<span class="at">power =</span> <span class="fl">0.8</span>,<span class="at">type =</span> <span class="st">"paired"</span>,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Paired t test power calculation 

              n = 10.77326
              d = 0.95
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number of *pairs*</code></pre>
</div>
</div>
<p><strong>RESPONDE:</strong> ¿Qué se puede concluir de ambas salidas? Justifique reportando a partir de las salidas.</p>
</section>
<section id="anexos.-resultados-descriptivos.-1" class="level3">
<h3 class="anchored" data-anchor-id="anexos.-resultados-descriptivos.-1">Anexos. Resultados descriptivos.</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Hacer un gráfico de Cajas.</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>Datos <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">ID=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">times =</span> <span class="dv">2</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Grupo, <span class="at">y =</span> Residuos))<span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_boxplot</span>(<span class="at">geom=</span><span class="st">'errorbar'</span>, <span class="at">linetype=</span><span class="dv">1</span>, <span class="at">width=</span><span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"lightpink"</span>,<span class="at">color=</span><span class="st">"black"</span>,<span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.shape =</span> <span class="dv">21</span>)<span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> ID),<span class="at">color =</span> <span class="st">"darkgray"</span>, <span class="at">size =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>,<span class="at">fill=</span><span class="st">"#ffa69e"</span>, <span class="at">size=</span><span class="fl">2.5</span>, <span class="at">color=</span><span class="st">"red3"</span>)<span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">"point"</span>, <span class="at">size=</span><span class="fl">1.5</span>, <span class="at">shape=</span><span class="dv">8</span>)<span class="sc">+</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span> </span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"Ácido sórbico (ppm)"</span>,<span class="at">x=</span><span class="st">""</span>)<span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_compare_means</span>(<span class="at">method =</span> <span class="st">"t.test"</span>, <span class="at">label =</span> <span class="st">"p.signif"</span>,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>                     <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method.args=</span><span class="fu">list</span>(<span class="at">alternative =</span> <span class="st">"two.sided"</span>),</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>                     <span class="at">comparisons =</span><span class="fu">list</span>(<span class="fu">c</span>(<span class="st">"Al sumergirlo"</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"Después de almacenado"</span>)))<span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="cn">NA</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Guia2_pHR_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="624"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medidas de resumen. </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descriptr)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ds_group_summary</span>(<span class="at">data =</span> Datos, <span class="at">group_by =</span> Grupo, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">cols =</span>  Residuos)<span class="sc">$</span>stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Statistic/Levels Al sumergirlo Después de almacenado
1                  Obs          8.00                  8.00
2              Minimum        224.00                 96.00
3              Maximum       1400.00                689.00
4                 Mean        583.50                384.88
5               Median        517.00                383.00
6                 Mode        224.00                 96.00
7       Std. Deviation        370.82                225.79
8             Variance     137504.86              50982.70
9             Skewness          1.72                 -0.03
10            Kurtosis          3.67                 -1.66
11      Uncorrected SS    3686312.00            1541909.00
12        Corrected SS     962534.00             356878.88
13     Coeff Variation         63.55                 58.67
14     Std. Error Mean        131.10                 79.83
15               Range       1176.00                593.00
16 Interquartile Range        297.50                373.00</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>